"""Create tables owners, pets

Revision ID: 2c53fa02739b
Revises: 9b1136e7ca65
Create Date: 2026-04-10 15:09:30.096932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c53fa02739b'
down_revision = '9b1136e7ca65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
